import type { PrismaSchemaFieldDefinition, PrismaSchemaModelDefinition } from '../types';

export const AUTH_PRISMA_SCHEMA_MODELS: PrismaSchemaModelDefinition[] = [
  {
    name: 'AuthUser',
    description: 'Shared authentication user record',
    fields: [
      { name: 'id', type: 'String', attributes: ['@id', '@default(cuid())'] },
      { name: 'email', type: 'String?', attributes: ['@unique'] },
      { name: 'name', type: 'String?' },
      { name: 'image', type: 'String?' },
      { name: 'isAdmin', type: 'Boolean', attributes: ['@default(false)'] },
      { name: 'tokenBalance', type: 'Int', attributes: ['@default(0)'] },
      { name: 'isVip', type: 'Boolean', attributes: ['@default(false)'] },
      { name: 'createdAt', type: 'DateTime', attributes: ['@default(now())'] },
      { name: 'updatedAt', type: 'DateTime', attributes: ['@updatedAt'] },
    ],
    blockAttributes: ['@@index([email])'],
  },
  {
    name: 'AuthMembership',
    description: 'Subscription membership snapshot',
    fields: [
      { name: 'id', type: 'String', attributes: ['@id', '@default(cuid())'] },
      { name: 'userId', type: 'String', attributes: ['@unique'] },
      { name: 'plan', type: 'String' },
      { name: 'status', type: 'String' },
      { name: 'startsAt', type: 'DateTime?' },
      { name: 'endsAt', type: 'DateTime?' },
      { name: 'createdAt', type: 'DateTime', attributes: ['@default(now())'] },
      { name: 'updatedAt', type: 'DateTime', attributes: ['@updatedAt'] },
    ],
    blockAttributes: ['@@index([userId])'],
  },
  {
    name: 'AuthOrder',
    description: 'Commerce order record',
    fields: [
      { name: 'id', type: 'String', attributes: ['@id', '@default(cuid())'] },
      { name: 'userId', type: 'String' },
      { name: 'kind', type: 'String' },
      { name: 'status', type: 'String' },
      { name: 'amount', type: 'Int' },
      { name: 'currency', type: 'String', attributes: ['@default("CNY")'] },
      { name: 'payload', type: 'Json?' },
      { name: 'createdAt', type: 'DateTime', attributes: ['@default(now())'] },
      { name: 'updatedAt', type: 'DateTime', attributes: ['@updatedAt'] },
    ],
    blockAttributes: ['@@index([userId])'],
  },
  {
    name: 'AuthSubscription',
    description: 'Commerce subscription record',
    fields: [
      { name: 'id', type: 'String', attributes: ['@id', '@default(cuid())'] },
      { name: 'userId', type: 'String' },
      { name: 'productId', type: 'String' },
      { name: 'status', type: 'String' },
      { name: 'interval', type: 'String' },
      { name: 'startsAt', type: 'DateTime?' },
      { name: 'endsAt', type: 'DateTime?' },
      { name: 'createdAt', type: 'DateTime', attributes: ['@default(now())'] },
      { name: 'updatedAt', type: 'DateTime', attributes: ['@updatedAt'] },
    ],
    blockAttributes: ['@@index([userId])', '@@index([productId])'],
  },
  {
    name: 'AuthInvoice',
    description: 'Commerce invoice record',
    fields: [
      { name: 'id', type: 'String', attributes: ['@id', '@default(cuid())'] },
      { name: 'userId', type: 'String' },
      { name: 'orderId', type: 'String?' },
      { name: 'invoiceNo', type: 'String', attributes: ['@unique'] },
      { name: 'status', type: 'String' },
      { name: 'amount', type: 'Int' },
      { name: 'createdAt', type: 'DateTime', attributes: ['@default(now())'] },
      { name: 'updatedAt', type: 'DateTime', attributes: ['@updatedAt'] },
    ],
    blockAttributes: ['@@index([userId])', '@@index([orderId])'],
  },
];

function renderField(field: PrismaSchemaFieldDefinition): string {
  const attributes = field.attributes?.length ? ` ${field.attributes.join(' ')}` : '';
  return `  ${field.name} ${field.type}${attributes}`;
}

function renderModel(model: PrismaSchemaModelDefinition): string {
  const lines = [
    `/// ${model.description}`,
    `model ${model.name} {`,
    ...model.fields.map(renderField),
  ];

  if (model.blockAttributes?.length) {
    lines.push(...model.blockAttributes.map((attribute) => `  ${attribute}`));
  }

  lines.push('}');
  return lines.join('\n');
}

export function buildAuthPrismaSchemaTemplate(models: PrismaSchemaModelDefinition[] = AUTH_PRISMA_SCHEMA_MODELS): string {
  return [
    '// generated by @foldspace-fe/casdoor-next-auth-kit',
    '// merge these models into the host Prisma schema if you want a dedicated auth module',
    '',
    ...models.map(renderModel),
  ].join('\n\n');
}
