    import path from 'node:path';
    import fs from 'node:fs';
    import { exists, read, writeGeneratedFile, preserveCustomBlock } from './fs';
    import { apiProxyRouteTemplate, callbackRouteTemplate, commerceProxyRouteTemplate, envExampleTemplate, loginRouteTemplate, logoutRouteTemplate, nextAuthRouteTemplate, signupRouteTemplate } from './templates';

    const projectRoot = process.cwd();
    const targets = [
      ['app/auth/login/route.ts', loginRouteTemplate],
      ['app/auth/signup/route.ts', signupRouteTemplate],
      ['app/auth/api/[...path]/route.ts', apiProxyRouteTemplate],
      ['app/api/auth/[...nextauth]/route.ts', nextAuthRouteTemplate],
      ['app/callback/route.ts', callbackRouteTemplate],
      ['app/logout/route.ts', logoutRouteTemplate],
      ['app/api/casdoor/commerce/[...path]/route.ts', commerceProxyRouteTemplate]
    ] as const;

    export async function initProject() {
      for (const [rel, factory] of targets) {
        const filePath = path.join(projectRoot, rel);
        if (!exists(filePath)) {
          writeGeneratedFile(filePath, factory());
        }
      }
      const envExample = path.join(projectRoot, '.env.example');
      if (!exists(envExample)) {
        writeGeneratedFile(envExample, envExampleTemplate());
      }
      console.log('Initialized casdoor-next-auth-kit route shells.');
    }

    export async function updateProject() {
      for (const [rel, factory] of targets) {
        const filePath = path.join(projectRoot, rel);
        const next = '// generated by @foldspace/casdoor-next-auth-kit\n' + factory();
        if (!exists(filePath)) {
          writeGeneratedFile(filePath, factory());
          continue;
        }
        const current = read(filePath);
        const updated = preserveCustomBlock(current, next);
        if (current !== updated) {
          fs.writeFileSync(filePath, updated, 'utf8');
        }
      }
      console.log('Updated managed route shells.');
    }

    export async function checkProject() {
      const missing = targets.filter(([rel]) => !exists(path.join(projectRoot, rel))).map(([rel]) => rel);
      if (missing.length > 0) {
        console.error('Missing generated files:');
        for (const rel of missing) console.error('- ' + rel);
        process.exitCode = 1;
        return;
      }
      console.log('All generated route shells are present.');
    }
